# JSON Body 예시

url: https://jsonplaceholder.typicode.com/posts
method: POST
requests: 3
concurrency: 1
delay: 1

# Query Parameters (선택사항)
query_params:
  userId: "1"
  page: "1"

headers:
  Content-Type: application/json
  User-Agent: go-watch/1.0

# Body 설정
# body_type: json, form, xml, raw
body_type: json

# json/form 타입: map 형태로 작성
body:
  title: "테스트 포스트"
  body: "내용입니다"
  userId: 1

# xml/raw 타입: 문자열로 작성
# body: |
#   {
#     "title": "테스트",
#     "body": "내용"
#   }

output_file: "results.jsonl"
save_response_body: true
