# Raw Text Body 예시

url: https://httpbin.org/post
method: POST
requests: 1
concurrency: 1
delay: 0

headers:
  Content-Type: text/plain

# Raw 일반 텍스트
body_type: raw
body: |
  가나다라마바사

output_file: "results_raw.jsonl"
save_response_body: true
